// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"net/http"
	"sync"

	"github.com/BrandonWade/enako/api/controllers"
)

type FakeAccountController struct {
	ActivateAccountStub        func(http.ResponseWriter, *http.Request)
	activateAccountMutex       sync.RWMutex
	activateAccountArgsForCall []struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}
	RegisterUserStub        func(http.ResponseWriter, *http.Request)
	registerUserMutex       sync.RWMutex
	registerUserArgsForCall []struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}
	RequestPasswordResetStub        func(http.ResponseWriter, *http.Request)
	requestPasswordResetMutex       sync.RWMutex
	requestPasswordResetArgsForCall []struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}
	ResetPasswordStub        func(http.ResponseWriter, *http.Request)
	resetPasswordMutex       sync.RWMutex
	resetPasswordArgsForCall []struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}
	SetPasswordResetTokenStub        func(http.ResponseWriter, *http.Request)
	setPasswordResetTokenMutex       sync.RWMutex
	setPasswordResetTokenArgsForCall []struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAccountController) ActivateAccount(arg1 http.ResponseWriter, arg2 *http.Request) {
	fake.activateAccountMutex.Lock()
	fake.activateAccountArgsForCall = append(fake.activateAccountArgsForCall, struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}{arg1, arg2})
	fake.recordInvocation("ActivateAccount", []interface{}{arg1, arg2})
	fake.activateAccountMutex.Unlock()
	if fake.ActivateAccountStub != nil {
		fake.ActivateAccountStub(arg1, arg2)
	}
}

func (fake *FakeAccountController) ActivateAccountCallCount() int {
	fake.activateAccountMutex.RLock()
	defer fake.activateAccountMutex.RUnlock()
	return len(fake.activateAccountArgsForCall)
}

func (fake *FakeAccountController) ActivateAccountCalls(stub func(http.ResponseWriter, *http.Request)) {
	fake.activateAccountMutex.Lock()
	defer fake.activateAccountMutex.Unlock()
	fake.ActivateAccountStub = stub
}

func (fake *FakeAccountController) ActivateAccountArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.activateAccountMutex.RLock()
	defer fake.activateAccountMutex.RUnlock()
	argsForCall := fake.activateAccountArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAccountController) RegisterUser(arg1 http.ResponseWriter, arg2 *http.Request) {
	fake.registerUserMutex.Lock()
	fake.registerUserArgsForCall = append(fake.registerUserArgsForCall, struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}{arg1, arg2})
	fake.recordInvocation("RegisterUser", []interface{}{arg1, arg2})
	fake.registerUserMutex.Unlock()
	if fake.RegisterUserStub != nil {
		fake.RegisterUserStub(arg1, arg2)
	}
}

func (fake *FakeAccountController) RegisterUserCallCount() int {
	fake.registerUserMutex.RLock()
	defer fake.registerUserMutex.RUnlock()
	return len(fake.registerUserArgsForCall)
}

func (fake *FakeAccountController) RegisterUserCalls(stub func(http.ResponseWriter, *http.Request)) {
	fake.registerUserMutex.Lock()
	defer fake.registerUserMutex.Unlock()
	fake.RegisterUserStub = stub
}

func (fake *FakeAccountController) RegisterUserArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.registerUserMutex.RLock()
	defer fake.registerUserMutex.RUnlock()
	argsForCall := fake.registerUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAccountController) RequestPasswordReset(arg1 http.ResponseWriter, arg2 *http.Request) {
	fake.requestPasswordResetMutex.Lock()
	fake.requestPasswordResetArgsForCall = append(fake.requestPasswordResetArgsForCall, struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}{arg1, arg2})
	fake.recordInvocation("RequestPasswordReset", []interface{}{arg1, arg2})
	fake.requestPasswordResetMutex.Unlock()
	if fake.RequestPasswordResetStub != nil {
		fake.RequestPasswordResetStub(arg1, arg2)
	}
}

func (fake *FakeAccountController) RequestPasswordResetCallCount() int {
	fake.requestPasswordResetMutex.RLock()
	defer fake.requestPasswordResetMutex.RUnlock()
	return len(fake.requestPasswordResetArgsForCall)
}

func (fake *FakeAccountController) RequestPasswordResetCalls(stub func(http.ResponseWriter, *http.Request)) {
	fake.requestPasswordResetMutex.Lock()
	defer fake.requestPasswordResetMutex.Unlock()
	fake.RequestPasswordResetStub = stub
}

func (fake *FakeAccountController) RequestPasswordResetArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.requestPasswordResetMutex.RLock()
	defer fake.requestPasswordResetMutex.RUnlock()
	argsForCall := fake.requestPasswordResetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAccountController) ResetPassword(arg1 http.ResponseWriter, arg2 *http.Request) {
	fake.resetPasswordMutex.Lock()
	fake.resetPasswordArgsForCall = append(fake.resetPasswordArgsForCall, struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}{arg1, arg2})
	fake.recordInvocation("ResetPassword", []interface{}{arg1, arg2})
	fake.resetPasswordMutex.Unlock()
	if fake.ResetPasswordStub != nil {
		fake.ResetPasswordStub(arg1, arg2)
	}
}

func (fake *FakeAccountController) ResetPasswordCallCount() int {
	fake.resetPasswordMutex.RLock()
	defer fake.resetPasswordMutex.RUnlock()
	return len(fake.resetPasswordArgsForCall)
}

func (fake *FakeAccountController) ResetPasswordCalls(stub func(http.ResponseWriter, *http.Request)) {
	fake.resetPasswordMutex.Lock()
	defer fake.resetPasswordMutex.Unlock()
	fake.ResetPasswordStub = stub
}

func (fake *FakeAccountController) ResetPasswordArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.resetPasswordMutex.RLock()
	defer fake.resetPasswordMutex.RUnlock()
	argsForCall := fake.resetPasswordArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAccountController) SetPasswordResetToken(arg1 http.ResponseWriter, arg2 *http.Request) {
	fake.setPasswordResetTokenMutex.Lock()
	fake.setPasswordResetTokenArgsForCall = append(fake.setPasswordResetTokenArgsForCall, struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}{arg1, arg2})
	fake.recordInvocation("SetPasswordResetToken", []interface{}{arg1, arg2})
	fake.setPasswordResetTokenMutex.Unlock()
	if fake.SetPasswordResetTokenStub != nil {
		fake.SetPasswordResetTokenStub(arg1, arg2)
	}
}

func (fake *FakeAccountController) SetPasswordResetTokenCallCount() int {
	fake.setPasswordResetTokenMutex.RLock()
	defer fake.setPasswordResetTokenMutex.RUnlock()
	return len(fake.setPasswordResetTokenArgsForCall)
}

func (fake *FakeAccountController) SetPasswordResetTokenCalls(stub func(http.ResponseWriter, *http.Request)) {
	fake.setPasswordResetTokenMutex.Lock()
	defer fake.setPasswordResetTokenMutex.Unlock()
	fake.SetPasswordResetTokenStub = stub
}

func (fake *FakeAccountController) SetPasswordResetTokenArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.setPasswordResetTokenMutex.RLock()
	defer fake.setPasswordResetTokenMutex.RUnlock()
	argsForCall := fake.setPasswordResetTokenArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAccountController) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.activateAccountMutex.RLock()
	defer fake.activateAccountMutex.RUnlock()
	fake.registerUserMutex.RLock()
	defer fake.registerUserMutex.RUnlock()
	fake.requestPasswordResetMutex.RLock()
	defer fake.requestPasswordResetMutex.RUnlock()
	fake.resetPasswordMutex.RLock()
	defer fake.resetPasswordMutex.RUnlock()
	fake.setPasswordResetTokenMutex.RLock()
	defer fake.setPasswordResetTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAccountController) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ controllers.AccountController = new(FakeAccountController)
