// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"net/http"
	"sync"

	"github.com/BrandonWade/enako/api/controllers"
)

type FakeChangeEmailController struct {
	RequestEmailChangeStub        func(http.ResponseWriter, *http.Request)
	requestEmailChangeMutex       sync.RWMutex
	requestEmailChangeArgsForCall []struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChangeEmailController) RequestEmailChange(arg1 http.ResponseWriter, arg2 *http.Request) {
	fake.requestEmailChangeMutex.Lock()
	fake.requestEmailChangeArgsForCall = append(fake.requestEmailChangeArgsForCall, struct {
		arg1 http.ResponseWriter
		arg2 *http.Request
	}{arg1, arg2})
	fake.recordInvocation("RequestEmailChange", []interface{}{arg1, arg2})
	fake.requestEmailChangeMutex.Unlock()
	if fake.RequestEmailChangeStub != nil {
		fake.RequestEmailChangeStub(arg1, arg2)
	}
}

func (fake *FakeChangeEmailController) RequestEmailChangeCallCount() int {
	fake.requestEmailChangeMutex.RLock()
	defer fake.requestEmailChangeMutex.RUnlock()
	return len(fake.requestEmailChangeArgsForCall)
}

func (fake *FakeChangeEmailController) RequestEmailChangeCalls(stub func(http.ResponseWriter, *http.Request)) {
	fake.requestEmailChangeMutex.Lock()
	defer fake.requestEmailChangeMutex.Unlock()
	fake.RequestEmailChangeStub = stub
}

func (fake *FakeChangeEmailController) RequestEmailChangeArgsForCall(i int) (http.ResponseWriter, *http.Request) {
	fake.requestEmailChangeMutex.RLock()
	defer fake.requestEmailChangeMutex.RUnlock()
	argsForCall := fake.requestEmailChangeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeChangeEmailController) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.requestEmailChangeMutex.RLock()
	defer fake.requestEmailChangeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChangeEmailController) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ controllers.ChangeEmailController = new(FakeChangeEmailController)
