version: '3'

services:
    # mysql:
    #     image: 'mysql:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        volumes:
            - ./api:./api
        ports:
            - '8080:8080'
