version: '3'

services:
    db:
        build:
            dockerfile: Dockerfile.dev
            context: ./api/database/
        container_name: enako-db
        volumes:
            - ./api/database:/database
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=enako
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        container_name: enako-api
        depends_on:
            - 'db'
        volumes:
            - ./api:/app
        ports:
            - '8000:8000'
        environment:
            - API_HOST=${API_HOST:?err}
            - COOKIE_SECRET=${COOKIE_SECRET:?err}
            - CSRF_SECRET=${CSRF_SECRET:?err}
            - DB_HOST=${DB_HOST:?err}
            - DB_PORT=${DB_PORT:?err}
            - DB_USERNAME=${DB_USERNAME:?err}
            - DB_PASSWORD=${DB_PASSWORD:?err}
            - DB_DATABASE=${DB_DATABASE:?err}
            - MAILJET_PUBLIC_KEY=${MAILJET_PUBLIC_KEY:?err}
            - MAILJET_PRIVATE_KEY=${MAILJET_PRIVATE_KEY:?err}
            - ENAKO_DOMAIN=${ENAKO_DOMAIN:?err}
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        container_name: enako-nginx
        ports:
            - '8100:80'
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        container_name: enako-client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CI=true
