version: '3'

services:
    db:
        build:
            dockerfile: Dockerfile.dev
            context: ./api/database/
        container_name: enako-db
        volumes:
            - ./api/database:/database
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=enako
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        container_name: enako-api
        depends_on:
            - 'db'
        volumes:
            - ./api:/app
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=enako-db
            - DB_PORT=3306
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - DB_DATABASE=enako
            - COOKIE_SECRET=super-secret-key
            - CSRF_SECRET=another-super-secret-key
            - MAIL_HOST=enako-mail
            - MAIL_PORT=1025
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        container_name: enako-nginx
        ports:
            - '8100:80'
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        container_name: enako-client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CI=true
    mailhog:
        image: schickling/mailcatcher:latest
        container_name: enako-mail
        ports:
            # - 1025:1025
            - 1080:1080
