version: '3'

services:
    db:
        image: 'mysql:latest'
        container_name: enako-db
        volumes:
            - ./api/database:/database
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=enako
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./api
        container_name: enako-api
        depends_on:
            - 'db'
        volumes:
            - ./api:/go/src/github.com/BrandonWade/enako/api
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=enako-db
            - DB_PORT=3306
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - DB_DATABASE=enako
            - COOKIE_SECRET=super-secret-key
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        container_name: enako-nginx
        ports:
            - '8100:80'
    client:
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        container_name: enako-client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - CI=true
