version: 2
jobs:
    build:
        docker:
            - image: golang:1.14
        working_directory: /app
        steps:
            - checkout
            - run:
                  name: Fetching dependencies
                  command: go get -v github.com/onsi/ginkgo/ginkgo && go get -v github.com/onsi/gomega && go get -u golang.org/x/lint/golint
            - run:
                  name: Running unit tests (backend)
                  command: cd api && ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
            - run:
                  name: Running linter (backend)
                  command: golint -set_exit_status ./...
