// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/BrandonWade/enako/api/services"
)

type FakeAuthService struct {
	ActivateAccountStub        func(string) (bool, error)
	activateAccountMutex       sync.RWMutex
	activateAccountArgsForCall []struct {
		arg1 string
	}
	activateAccountReturns struct {
		result1 bool
		result2 error
	}
	activateAccountReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	CreateAccountStub        func(string, string, string) (int64, string, error)
	createAccountMutex       sync.RWMutex
	createAccountArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 string
	}
	createAccountReturns struct {
		result1 int64
		result2 string
		result3 error
	}
	createAccountReturnsOnCall map[int]struct {
		result1 int64
		result2 string
		result3 error
	}
	VerifyAccountStub        func(string, string) (int64, error)
	verifyAccountMutex       sync.RWMutex
	verifyAccountArgsForCall []struct {
		arg1 string
		arg2 string
	}
	verifyAccountReturns struct {
		result1 int64
		result2 error
	}
	verifyAccountReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthService) ActivateAccount(arg1 string) (bool, error) {
	fake.activateAccountMutex.Lock()
	ret, specificReturn := fake.activateAccountReturnsOnCall[len(fake.activateAccountArgsForCall)]
	fake.activateAccountArgsForCall = append(fake.activateAccountArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ActivateAccount", []interface{}{arg1})
	fake.activateAccountMutex.Unlock()
	if fake.ActivateAccountStub != nil {
		return fake.ActivateAccountStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.activateAccountReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthService) ActivateAccountCallCount() int {
	fake.activateAccountMutex.RLock()
	defer fake.activateAccountMutex.RUnlock()
	return len(fake.activateAccountArgsForCall)
}

func (fake *FakeAuthService) ActivateAccountCalls(stub func(string) (bool, error)) {
	fake.activateAccountMutex.Lock()
	defer fake.activateAccountMutex.Unlock()
	fake.ActivateAccountStub = stub
}

func (fake *FakeAuthService) ActivateAccountArgsForCall(i int) string {
	fake.activateAccountMutex.RLock()
	defer fake.activateAccountMutex.RUnlock()
	argsForCall := fake.activateAccountArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthService) ActivateAccountReturns(result1 bool, result2 error) {
	fake.activateAccountMutex.Lock()
	defer fake.activateAccountMutex.Unlock()
	fake.ActivateAccountStub = nil
	fake.activateAccountReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthService) ActivateAccountReturnsOnCall(i int, result1 bool, result2 error) {
	fake.activateAccountMutex.Lock()
	defer fake.activateAccountMutex.Unlock()
	fake.ActivateAccountStub = nil
	if fake.activateAccountReturnsOnCall == nil {
		fake.activateAccountReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.activateAccountReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthService) CreateAccount(arg1 string, arg2 string, arg3 string) (int64, string, error) {
	fake.createAccountMutex.Lock()
	ret, specificReturn := fake.createAccountReturnsOnCall[len(fake.createAccountArgsForCall)]
	fake.createAccountArgsForCall = append(fake.createAccountArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 string
	}{arg1, arg2, arg3})
	fake.recordInvocation("CreateAccount", []interface{}{arg1, arg2, arg3})
	fake.createAccountMutex.Unlock()
	if fake.CreateAccountStub != nil {
		return fake.CreateAccountStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	fakeReturns := fake.createAccountReturns
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeAuthService) CreateAccountCallCount() int {
	fake.createAccountMutex.RLock()
	defer fake.createAccountMutex.RUnlock()
	return len(fake.createAccountArgsForCall)
}

func (fake *FakeAuthService) CreateAccountCalls(stub func(string, string, string) (int64, string, error)) {
	fake.createAccountMutex.Lock()
	defer fake.createAccountMutex.Unlock()
	fake.CreateAccountStub = stub
}

func (fake *FakeAuthService) CreateAccountArgsForCall(i int) (string, string, string) {
	fake.createAccountMutex.RLock()
	defer fake.createAccountMutex.RUnlock()
	argsForCall := fake.createAccountArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeAuthService) CreateAccountReturns(result1 int64, result2 string, result3 error) {
	fake.createAccountMutex.Lock()
	defer fake.createAccountMutex.Unlock()
	fake.CreateAccountStub = nil
	fake.createAccountReturns = struct {
		result1 int64
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthService) CreateAccountReturnsOnCall(i int, result1 int64, result2 string, result3 error) {
	fake.createAccountMutex.Lock()
	defer fake.createAccountMutex.Unlock()
	fake.CreateAccountStub = nil
	if fake.createAccountReturnsOnCall == nil {
		fake.createAccountReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 string
			result3 error
		})
	}
	fake.createAccountReturnsOnCall[i] = struct {
		result1 int64
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeAuthService) VerifyAccount(arg1 string, arg2 string) (int64, error) {
	fake.verifyAccountMutex.Lock()
	ret, specificReturn := fake.verifyAccountReturnsOnCall[len(fake.verifyAccountArgsForCall)]
	fake.verifyAccountArgsForCall = append(fake.verifyAccountArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("VerifyAccount", []interface{}{arg1, arg2})
	fake.verifyAccountMutex.Unlock()
	if fake.VerifyAccountStub != nil {
		return fake.VerifyAccountStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.verifyAccountReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAuthService) VerifyAccountCallCount() int {
	fake.verifyAccountMutex.RLock()
	defer fake.verifyAccountMutex.RUnlock()
	return len(fake.verifyAccountArgsForCall)
}

func (fake *FakeAuthService) VerifyAccountCalls(stub func(string, string) (int64, error)) {
	fake.verifyAccountMutex.Lock()
	defer fake.verifyAccountMutex.Unlock()
	fake.VerifyAccountStub = stub
}

func (fake *FakeAuthService) VerifyAccountArgsForCall(i int) (string, string) {
	fake.verifyAccountMutex.RLock()
	defer fake.verifyAccountMutex.RUnlock()
	argsForCall := fake.verifyAccountArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeAuthService) VerifyAccountReturns(result1 int64, result2 error) {
	fake.verifyAccountMutex.Lock()
	defer fake.verifyAccountMutex.Unlock()
	fake.VerifyAccountStub = nil
	fake.verifyAccountReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthService) VerifyAccountReturnsOnCall(i int, result1 int64, result2 error) {
	fake.verifyAccountMutex.Lock()
	defer fake.verifyAccountMutex.Unlock()
	fake.VerifyAccountStub = nil
	if fake.verifyAccountReturnsOnCall == nil {
		fake.verifyAccountReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.verifyAccountReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeAuthService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.activateAccountMutex.RLock()
	defer fake.activateAccountMutex.RUnlock()
	fake.createAccountMutex.RLock()
	defer fake.createAccountMutex.RUnlock()
	fake.verifyAccountMutex.RLock()
	defer fake.verifyAccountMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.AuthService = new(FakeAuthService)
